[package]
name = "ansi-flip-book"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
regex = "1"
subprocess = "0.2"
shell-escape = "0.1"
nix = "0.26"